Clang tidy check

diff --git a/.github/workflows/cmake.yml b/.github/workflows/cmake.yml
--- a/.github/workflows/cmake.yml
+++ b/.github/workflows/cmake.yml
@@ -55,3 +55,9 @@ jobs:
 
       - name: Build TimeIT
         run: cmake --build --preset ninja-multi-release
+
+      - uses: ZedThree/clang-tidy-review@v0.10.0
+        id: review
+      # If there are any comments, fail the check
+      - if: steps.review.outputs.total_comments > 0
+        run: exit 1
